alquiler/urls.py
from unicodedata import name
from django.urls import path
from .views import HomeView,ContactPage,UbicacionPage, AddCanchaView,CanchasView,EditCanchaView,DeleteCanchaView,ReservasView,ReservasHechasView,ReservarCanchaView,ReservaCanchaConfirmadaView
from . import views

urlpatterns = [
#    path('', views.index, name = "home"),
    path('',HomeView.as_view(), name="home"),
    path('contact/', ContactPage, name="contact"),
    path('ubicacion/', UbicacionPage, name="ubicacion"),
    path('agregar_cancha/', AddCanchaView.as_view(), name="agregar_cancha"),
    path('canchas/', CanchasView.as_view(), name="canchas"),
    path('canchas/editar_cancha/<int:pk>', EditCanchaView.as_view(), name="editar_cancha"),
    path('canchas/borrar_cancha/<int:pk>', DeleteCanchaView.as_view(), name="borrar_cancha"),
    path('reservas/', ReservasView.as_view(), name="reservas"),
    path('reservas_hechas/<int:pag>', ReservasHechasView.as_view(), name="reservas_hechas"),
    path('reservar_cancha/<int:idcancha>/<int:idhora>',ReservarCanchaView.as_view(), name="reservar_cancha"),
    path('reserva_confirmada',ReservaCanchaConfirmadaView,name="reserva_confirmada")
]

f5web/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

handler404 = 'alquiler.views.error_404_view'

urlpatterns = [
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$',serve,{'document_root':settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('alquiler.urls')),
    path('members/', include('django.contrib.auth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alquiler/models.py
from dataclasses import Field
from datetime import datetime
from operator import index
from django.db import models
from django.contrib.auth.models import User
from django.forms import IntegerField
from django.urls import reverse
from datetime import datetime

# Create your models here.
class Horario(models.Model):
    id = models.AutoField(primary_key=True,auto_created = True, serialize = False)
    #solo pueden haber horas en las que este abierto el lugar
    hora = models.IntegerField(null=False, blank=False)


class Cancha(models.Model):
    id = models.AutoField(primary_key=True,auto_created = True, serialize = False)
    #nombre de la cancha
    nombre = models.CharField(max_length=255, null=False, blank=False)
    #capacidad si es de futbol 5 o futbol 7
    capacidad = models.CharField(max_length=255, null=False, blank=False)
    #esta habilitada?
    habilitada = models.BooleanField(default=True)
    #quien creo o edito la cancha
    creador = models.ForeignKey(User, on_delete=models.CASCADE)
    #tipo de piso
    piso = models.CharField(max_length=255, null=False, blank=False, default="sintetico")
    #esta techada
    techada = models.BooleanField(default=True)
    #tiene iluminacion
    iluminacion = models.BooleanField(default=True)

    def horarios_disponible(self):
        fecha_actual = datetime.now().date()
        horarios = Horario.objects.all()
        reservas = Reserva.objects.all().filter(fecha = fecha_actual)
        horarios_disponibles = []

        for hor in horarios:
            horarios_disponibles.append(hor)

        for reserva in reservas:
            if(self.id == reserva.cancha.id):
               horarios_disponibles.remove(reserva.horario)
        
        return horarios_disponibles

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('home')

class Reserva(models.Model):
    id = models.AutoField(primary_key=True,auto_created = True, serialize = False)
    #nombre de quien crea la reserva
    nombre = models.CharField(max_length=255, null=False, blank=False)
    #numero telefono para contacto
    telefono = models.CharField(max_length=255, null=False, blank=False)
    #cancha elegida para crear la reserva
    cancha = models.ForeignKey(Cancha, on_delete=models.CASCADE)
    #fecha de la reserva
    fecha = models.DateField(auto_now_add=True)
    #horario
    horario = models.ForeignKey(Horario, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ("-id",)
    
    def __str__(self):
        return self.nombre

alquiler/forms.py
from email.policy import default
from unicodedata import name
from django import forms
from requests import request
from .models import Cancha, Horario, Reserva, User
from datetime import datetime

#forma del modelo del posteo
class CanchaForm(forms.ModelForm):
    class Meta:
        capacidad_opciones = [('Futbol 5','Futbol 5'), ('Futbol 7','Futbol 7'),]
        model = Cancha
        fields = ('nombre','capacidad','habilitada','creador','piso','techada','iluminacion')
        widgets = {
             'nombre':forms.TextInput(attrs={'class':'form-control'}),
             'capacidad':forms.Select(attrs={'class':'form-control'}, choices=capacidad_opciones),
             'piso':forms.TextInput(attrs={'class':'form-control'}),
             'creador':forms.Select(attrs={'class':'form-control'}),
            }

class EditCanchaForm(forms.ModelForm):
    class Meta:
        capacidad_opciones = [('Futbol 5','Futbol 5'), ('Futbol 7','Futbol 7'),]
        model = Cancha
        fields = ('nombre','capacidad','habilitada','creador','piso','techada','iluminacion')
        widgets = {
             'nombre':forms.TextInput(attrs={'class':'form-control'}),
             'capacidad':forms.Select(attrs={'class':'form-control'}, choices=capacidad_opciones),
             'piso':forms.TextInput(attrs={'class':'form-control'}),
             'creador':forms.Select(attrs={'class':'form-control'}),
            }

class ReservaForm(forms.ModelForm):
   
    class Meta:
        model = Reserva
        fields = ('nombre','telefono','cancha','horario')
        widgets = {
            'nombre':forms.TextInput(attrs={'class':'form-control'}),
            'telefono':forms.TextInput(attrs={'class':'form-control'}),
            'cancha':forms.Select(attrs={'class':'form-control'}),
            'horario':forms.Select(attrs={'class':'form-control'}),
        }

alquiler/views.py
from urllib import request
from django import http
from django.views import View
from django.views.generic import  ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Reserva, Cancha, Horario
from django.shortcuts import render
from django.core.mail import send_mail
from .forms import CanchaForm,EditCanchaForm,ReservaForm
from django.urls import reverse_lazy

# Create your views here.

class HomeView(ListView):
    #tipo de modelo
    model = Cancha
    #nombre de la plantilla
    template_name = 'home.html'

class ReservasView(ListView):
    #tipo de modelo
    model = Reserva
    #nombre de la plantilla
    template_name = 'reservas.html'
    #ordering = ['-post_date','-id']
    def get_context_data(self, *args, **kwargs):
        canchas = Cancha.objects.all()
        info = []
        for cancha in canchas:
            horarios_disponibles = cancha.horarios_disponible()
            
            

            inf = [ cancha , horarios_disponibles ]
            info.append(inf)
            horarios_disponibles = []
        context = super(ReservasView, self).get_context_data(*args, **kwargs)
        context["info"] = info
        return context

class AddCanchaView(CreateView):
    #modelo de la clase 
    model = Cancha
    #formas de que tomará el formulario
    form_class = CanchaForm
    template_name = 'agregar_cancha.html'
    success_url = reverse_lazy('canchas')

class CanchasView(ListView):
    model = Cancha
    template_name = 'cancha.html'
    def get_context_data(self, *args, **kwargs):
        canchas = Cancha.objects.all()
        context = super(CanchasView, self).get_context_data(*args, **kwargs)
        context["canchas"] = canchas
        return context

class EditCanchaView(UpdateView):
    model = Cancha
    form_class = EditCanchaForm
    template_name = 'editar_cancha.html'
    success_url = reverse_lazy('canchas')

class DeleteCanchaView(DeleteView):
    model = Cancha
    template_name = 'borrar_cancha.html'
    success_url = reverse_lazy('canchas')


class DeleteCanchaView(DeleteView):    
    model = Cancha
    template_name = 'borrar_cancha.html'


def UbicacionPage(request):
    return render(request, 'ubicacion.html')


def ContactPage(request):

    if request.method == "POST":
        nombre_contacto = request.POST['nombre']
        email_contacto = request.POST['email']
        mensaje_contacto = request.POST['mensaje']
        
        #enviar email
        send_mail(
            "Mensaje de " + nombre_contacto,
            mensaje_contacto + email_contacto,
            email_contacto,
            ['emailF5@gmail.com'],
            fail_silently=False,           
        )
        return render(request, 'contact.html')
    else:
        return render(request, 'contact.html')

class ReservasHechasView(ListView):
    #tipo de modelo
    model = Reserva
    #nombre de la plantilla
    template_name = 'reservas_hechas.html'

    def get_context_data(self, *args, **kwargs):
        reservas = Reserva.objects.all().order_by('-id')
        context = super(ReservasHechasView, self).get_context_data(*args, **kwargs)
        context["reservas"] = reservas
        return context

class ReservarCanchaView(CreateView):
    
    #modelo de la clase 
    model = Reserva
    #formas de que tomará el formulario
    form_class = ReservaForm
    template_name = 'reservar_cancha.html'
    def get_context_data(self, *args, **kwargs):
        canchas = Cancha.objects.all()
        horarios = Horario.objects.all()
        context = super(ReservarCanchaView, self).get_context_data(*args, **kwargs)
        context["canchas"] = canchas
        context["horarios"] = horarios
        return context

    success_url = reverse_lazy('reserva_confirmada')
    

def ReservaCanchaConfirmadaView(request):
    return render(request,'reserva_confirmada.html')
    
def error_404_view(request,exception):
    return render(request,'not_found_page.html')

alquiler/templates/agregar_cancha.html
{% extends 'base.html' %}
{% load static %}
<!--Titulo de la Página Principal -->
{% block title %}Crear una nueva Cancha{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid col-10 post-home agregar-cancha rounded-3">  
            <div class="text-center text-decoration-underline">
                <h1>Agregar Cancha</h1></br>
            </div>
            <!--Formulario Django-->
            <div class="container">
                <div class="form-group col-8 mx-auto">
                    <form method="POST">
                
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <button class="btn btn-primary w-50">Agregar Cancha</button>
                    </div>
                    </form>
                </div>
            </div>
            </br>
        </div>
    {% endif %}

{% endblock %}

alquiler/templates/base.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block meta %}
    {% endblock %}

    <!-- FOnt Awesome CSS-->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
     integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" 
     crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.0/css/all.min.css">
     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" 
    rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" 
    crossorigin="anonymous">
    <!-- CSS Custom -->
    <link href="{% static 'css/grande.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/mediano.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/chico.css' %}" rel="stylesheet" type="text/css">

    
    <title> {% block title %} {% endblock %}</title>
  </head>
  <body class="cuerpo">

      <!--NAVBAR-->
      <nav class="navbar navbar-expand-md navbar-dark bg-dark p-3">
          <div class="container-fluid text-inicio w-50">
            <div>
              <a class="navbar-brand " href="{% url 'home' %}">Cancha F5</a>
            </div>
            <button class="navbar-toggler " type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
            aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button> 
          </div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto text-opciones">
              <li class="nav-item">
                <a class="nav-link active rounded-3 pestaña text-center px-4" aria-current="page"
                 href="{% url 'home' %}">Inicio</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active rounded-3 pestaña text-center px-4" aria-current="page" 
                href="{% url 'reservas' %}">Reservar Cancha</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link active rounded-3 pestaña text-center px-4" aria-current="page" 
                href="{% url 'ubicacion' %}">Ubicacion</a>
              </li>

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle rounded-3 pestaña active text-center px-4" 
                href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Seguinos
                </a>
                <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                    <li class=""><a class="dropdown-item text-white text-center pestaña" 
                      href="https://www.instagram.com" target="_blank">Instagram <i class="fab fa-instagram"></i></a></li>
                    <li class=""><a class="dropdown-item text-white text-center pestaña"  
                      href="https://www.facebook.com" target="_blank">Facebook <i class="fab fa-facebook"></i></a></li>
                    <li class=""><a class="dropdown-item text-white text-center  pestaña" 
                      href="https://www.twitter.com" target="_blank">Twitter<i class="fab fa-twitter"></i></a></li>
                </ul>
              </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link pestaña" href="{% url 'agregar_cancha' %}">Agregar Cancha</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link pestaña" href="{% url 'canchas' %}">Ver Canchas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link pestaña" href="{% url 'reservas_hechas' 1 %}">Ver Reservas</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link pestaña" href="{% url 'logout' %}">Cerrar Sesion</a>
                </li>
              {% endif %} 
            </ul>
          </div>
      </nav>
     
    <!-- Contenido que se agrega desde el template -->
    <div class="container-fluid cotenido_principal m-0 p-0">
      {% block content %}
          
      {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="py-2 bg-dark w-100 text-center fixed-bottom">
      <div class="container-fluid py-2">
        <ul class="my-0 w-100 ">
          <div class="">
            <li class="list-inline-item "><a href="/" class="text-white textpie">Cancha F5</a></li>
            <li class="list-inline-item "><a href="{% url 'contact' %}" class="text-white textpie">Contacto</a></li>
            <li class="list-inline-item "><a href="{% url 'ubicacion' %}" class="text-white textpie">Ubicacion</a></li>
          </div>
        </ul>
      </div>
  </footer>

    <!-- Scripts Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

   
  </body>
</html>

alquiler/templates/borrar_cancha.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página Principal -->
{% block title %}Eliminar Cancha{% endblock %}

{% if user.is_authenticated %}
    {% block content %}
        <div class="container-fluid col-sm-6 post-home borrar-cancha rounded-3">
            <div class="modal-dialog modal-confirm ">
                <div class="modal-content">
                    <div class="form-group">
                        <form method="POST">
                            {% csrf_token %}{{ form.as_p }}
                            <div class="modal-header flex-column">
                                <div class="icon-box">
                                    <i class="material-icons"/>
                                </div>						
                                <h4 class="modal-title w-100">Seguro de borrar la cancha {{cancha.nombre}} ?</h4>	
                            </div>
                            
                            <div class="modal-body">
                                <p>La cancha se borrara definitivamente y luego no podra volver a verlo.</p>
                            </div>
                            
                            <div class="modal-footer justify-content-center">
                                <button type="button" class="btn btn-secondary" 
                                data-dismiss="modal">Cancelar</button>
                                <button type="submit" 
                                class="btn btn-danger">Borrar Cancha</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div> 
            {% endblock %}
        </div>
{% endif %}

alquiler/templates/cancha.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página Principal -->
{% block title %}Canchas{% endblock %}

{% if user.is_authenticated %}
    {% block content %}
        <div class="container-fluid col-12 col-sm-10 post-home rounded-3 mx-auto my-2 py-2">
            {% if canchas %}
                <div class="text-center text-decoration-underline">
                    <h2 class="my-4">Canchas Existentes: </h2>
                </div>
                <ul class="listasinestilo px-0">
                {% for cancha in canchas %}
                    <hr>
                    <div class="container-fluid texto-fondo py-2 rounded-3">                    
                        <li>
                            <h5><strong>{{ cancha.nombre }}</strong> : 
                                {{ cancha.capacidad }} -
                                {% if cancha.habilitada %} 
                                    Habilidata
                                {% else %}
                                    Deshabilitada
                                {% endif %}
                                - Piso: {{cancha.piso}} -
                                {% if cancha.techada %} 
                                    Techada
                                {% else %}
                                    Sin techo
                                {% endif %}
                                -
                                {% if cancha.iluminacion %} 
                                    Esta iluminacion
                                {% else %}
                                    No esta iluminada
                                {% endif %}
                                 - Creada por: {{ cancha.creador }} 
                                    <a href="{% url 'editar_cancha' cancha.pk %}">Editar</a>
                                    <a href="{% url 'borrar_cancha' cancha.pk %}">Borrar</a>
                            </h5>
                        </li>
                    </div>
                    
                {% endfor %}
                </ul>
            {% else%}
                <h2 class="text-center my-4">Aún no hay ninguna cancha en el sistema.</h2>
                <a class="btn-sm btn-lg btn-secondary" href="{% url 'agregar_cancha' %}">
                    Agregar Nueva Cancha
                </a>
                <div class="text-center">
                    <i class="far fa-laugh-beam my-4 fa-6x"></i>
                </div>
            {% endif %}
        </div>
    {% endblock %}

{% endif %}

alquiler/templates/contact.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página  -->
{% block title %}Contacto{% endblock %}

{% block content %}
<div class="container-fluid col-12 col-sm-10 fondotexto rounded-3 mx-auto contactpage">
    <div class="container-fluid post-home my-4 py-1 rounded-3">
        <h2 class="my-4 text-decoration-underline ">Contáctanos a través de las redes sociales:</h2>
        <ul class="listasinestilo mx-auto w-100 p-0 text-center w-100">
            <div class="container-fluid p-0 m-0 redcontact text-center list-inline-item">
                <i class="fab fa-instagram fa-4x"></i>
                <li class=""><a class="fs-3" href="" target="_blank">Instagram </a></li>
            </div>
            <div class="container-fluid p-0 m-0 redcontact text-center list-inline-item">
                <i class="fab fa-facebook-square fa-3x"></i>
                <li class=""><a class="fs-3" href="" target="_blank">Facebook</a></li>
            </div>
            <div class="container-fluid p-0 m-0 redcontact text-center list-inline-item">
                <i class="fab fa-twitter-square fa-3x"></i>
                <li class=""><a class="fs-3" href="" target="_blank">Twitter</a></li>
            </div>
        </ul>
    
        <hr>
        {% if nombre_contacto %}
        <div class="container-fluid text-center">
            <h2>{{ nombre_contacto }}, gracias por contactarnos</h2>
            <h4>El mensaje ha sido enviado correctamente.</h4>
            <br>
            <a href="{% url 'home' %}">Volver al inicio</a>
        </div>
        {% else %}
            <div class="container-fluid">
                <h2 class="my-2 text-decoration-underline">Contáctanos a través de los siguientes telefonos: </h2>
                <ul class="listasinestilo mx-auto w-100 p-0  w-100">
                    <div class="container-fluid p-0 mx-auto"> 
                        <li class="ml-4"><h4>Celular: (0343)+54100000 </h4></li>
                        <li class="ml-4"><h4>Fijo: (0343) +54132230 </h4></li>
                    </div>
                </ul>
            </div>
            <hr>
            <h2 class="my-2 text-decoration-underline">Envíanos un Correo: </h2>
            <div class="container-fluid col-12 col-sm-10 fondo-comentario rounded-3 mt-4 py-2">
                <div class="form-group">
                    <form  action="{% url 'contact' %}" method="post">
                        {% csrf_token %}
                        <p class="py-0 my-0">Nombre:</p>
                        <input type="text" class="form-control my-2" placeholder="Nombre y Apellido" name="nombre">
                        <p class="py-0 my-0">Email:</p>
                        <input type="email" class="form-control my-2" placeholder="ejemplo@ejemplo.ej" name="email">
                        <p class="py-0 my-0">Mensaje:</p>
                        <textarea class="form-control my-2" placeholder="Escribe tu mensaje..." name="mensaje"></textarea>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary w-50">Enviar Mensaje</button>
                        </div>
                    </form>
                </div>       
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

alquiler/templates/editar_cancha.html
{% extends 'base.html' %}
{% load static %}
<!--Titulo de la Página Principal -->
{% block title %}Editar Cancha{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid col-10 post-home editar-cancha rounded-3">  
            <div class="text-center text-decoration-underline">
                <h1>Editar Cancha</h1></br>
            </div>
            <!--Formulario Django-->
            <div class="container">
                <div class="form-group col-8 mx-auto">
                    <form method="POST">
                
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="text-center">
                        <button class="btn btn-primary w-50">Editar Cancha</button>
                    </div>
                    </form>
                </div>
            </div>
            </br>
        </div>
    {% endif %}

{% endblock %}

alquiler/templates/home.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página Principal -->
{% block title %} Cancha F5 {% endblock %}

{% block content %}

  <div class="container-fluid col-10 my-2">

    <div class="container-fluid text-center my-2">
      <p class="fs-3 text-uppercase">Complejo de Canchas Futbol 5</p>
    </div>

    <div class="text-center col-8 mx-auto">
      <button type="button" class="btn btn-secondary bg-secondary text-wrap text-uppercase mb-4 py-2" 
      style="width: 80%;">
        <a class="text-decoration-none" href="{% url 'reservas' %}" style="color:black">Reserva tu cancha de manera online</a>
      </buttton>
    </div>

    <!-- Carrusel de Imagenes-->
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
      <ol class="carousel-indicators">
        <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"></li>
        <li data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'images/foto-prueba-1.jpg' %}" class="d-block carrusel" alt="Foto de Kelly L en Pexels">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/foto-prueba-2.jpg' %}" class="d-block carrusel" alt="Foto 2">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Siguiente</span>
      </a>
    </div>
  
  </div>

{% endblock %}

alquiler/templates/not_found_page.html

{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página  -->
{% block title %} Pagina no encontrada {% endblock %}

{% block content %}
<div class="container-fluid col-10 my-2">
    <h5 class="text-center my-2">Disculpe, la página no existe...</h5>
    <div class="mx-auto px-0 ">
        <img src="{% static 'images/404.jpg' %}" class="mx-0 px-0 image_404" alt="404">
    </div>
    <div class="text-center my-3">
        <button type="button" class="btn btn-secondary btn-lg">
            <a href="{% url 'home' %}" 
                class="text-decoration-none text-white">
                Volver al Inicio
            </a>
        </button>
    </div>
</div>
{% endblock %}

alquiler/templates/reserva_confirmada.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página Principal -->
{% block title %} Reservar Cancha {% endblock %}

{% block content %}
    <div class="container-fluid post-home col-8 rounded-3 reservar-cancha text-center ">
        <div class="text-decoration-underline my-4">
            <h1>Cancha Reservada con Exito</h1><i class="fa-regular fa-circle-check fa-4x"></i>
        </div>
        <div class="text-center my-3">
            <button type="button" class="btn btn-secondary btn-lg">
                <a href="{% url 'home' %}" 
                    class="text-decoration-none text-white">
                    Volver al Inicio
                </a>
            </button>
        </div>
    </div>

{% endblock %}

alquiler/templates/reservar_cancha.html
{% extends 'base.html' %}
{% load static %}

<!--Titulo de la Página Principal -->
{% block title %} Reservar Cancha {% endblock %}

{% block content %}
    <div class="container-fluid post-home col-10 rounded-3 reservar-cancha">
        <div class="text-center text-decoration-underline my-4">
            <h1>Reserva tu Cancha</h1>
        </div>
            
            <div class="col-sm-8 mx-auto">
                <div class="form-group">
                    <form  method="post" action="">
                        
                        {% csrf_token %}

                        <p class="py-0 my-0">Nombre:</p>                        
                        <input type="text" name="nombre" value="" class="form-control" maxlength="255" required id="id_nombre">
                        
                        <p class="py-0 my-0">Teléfono:</p>                       
                        <input type="text" name="telefono" value="" class="form-control" maxlength="255" required id="id_telefono">
                    
                        <p class="py-0 my-0">Cancha: </p>
                        <select name="cancha" class="form-control">
                            {% for cancha in canchas %}
                                {% if cancha.id == request.resolver_match.kwargs.idcancha %}
                                    <option value="{{ cancha.id }}">{{ cancha.nombre }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        
                        <p class="py-0 my-0">Horario: </p>
                        <select name="horario" class="form-control">
                            {% for horario in horarios %}
                                {% if horario.id == request.resolver_match.kwargs.idhora %}
                                    <option value = "{{horario.id}}">{{ horario.hora }} Hs</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        
                        <div class="text-center py-4">
                            <button type="submit" class="btn btn-primary w-50">Reservar Cancha</button>
                        </div>
                    </form>
                </div>       
            </div>


        
        
    </div>

{% endblock %}